name: flutter_application_2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
   - assets/dice-images/dice-1.png
   - assets/dice-images/dice-2.png
   - assets/dice-images/dice-3.png
   - assets/dice-images/dice-4.png
   - assets/dice-images/dice-5.png
   - assets/dice-images/dice-6.png